# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: '**'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99'
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Setup headless environment
      run: |
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - name: Build with Gradle
      run: ./gradlew test
    - name: Style Code Report
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: CheckStyle
        path: build/reports/checkstyle/checkstyle.html
    - name: Test Coverage Build
      run: ./gradlew build jacocoTestReport
    - name: Test Coverage Upload
      uses: actions/upload-artifact@v2
      with:
       name: TestCoverage
       path: build/reports/jacoco/test/html/
    - name: Build
      uses: actions/upload-artifact@v2
      with:
       name: Build
       path: build/distributions/
